#!/usr/bin/env python

# Copyright (C) 2013,2022 Smithsonian Astrophysical Observatory
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

'''Make temperature map using stack of images'''

import sys

import numpy as np

import pycrates as pyc
import stk

# we don't know what's in the init string so we need to import *
from sherpa.astro.ui import *     # pylint: disable=wildcard-import
from sherpa.models import Parameter, ArithmeticModel
import ciao_contrib.logger_wrapper as lw

# must come after sherpa
import logging   # pylint: disable=wrong-import-order


TOOLNAME = "image_tempmap"
__REVISION__ = "10 January 2022"

logging.getLogger("sherpa").setLevel(logging.ERROR)

lw.initialize_logger(TOOLNAME)
VERB0 = lw.get_logger(TOOLNAME).verbose0
VERB1 = lw.get_logger(TOOLNAME).verbose1
VERB2 = lw.get_logger(TOOLNAME).verbose2
VERB3 = lw.get_logger(TOOLNAME).verbose3
VERB5 = lw.get_logger(TOOLNAME).verbose5


class ExposureMapStack(ArithmeticModel):
    """
    This is a special model for fitting x-ray counts extracted from
    images with an expsoure map.

    The idea is that a stack of counts (interger) images is input
    and a stack of exposure maps are then also input to act
    as a table model.

    There are no free parameters in the model; normalization is
    left upto the other model components.
    """

    def __init__(self, name='expstk'):
        """
        The sherpa base class does not allow additional
        parameters after initialization, so we setup the
        values we want, and then create the x,y indexs.

        x0,y0 are parameter of the model but are not allowed
        to vary (they must be explicitly set).
        """
        self.filename = None
        self._filenames = None
        self._crates = None
        self._livetime = None
        self.x0 = Parameter(name, "x0", 1, alwaysfrozen=True)
        self.y0 = Parameter(name, "y0", 1, alwaysfrozen=True)
        ArithmeticModel.__init__(self, name, (self.x0, self.y0))

    def __setattr__(self, name, value):
        """
        When the filename is set, load the data
        """
        ArithmeticModel.__setattr__(self, name, value)
        if (name == "filename") & (value is not None):
            self.load_expstk(self.filename)
            self.load_expimages()

    def __str__(self):
        """
        Include the file name when the model is printed.
        """
        return(ArithmeticModel.__str__(self) +
               "\n  File names:  " + str(self._filenames))

    def load_expstk(self, value):
        """
        Load the stack of exposure maps
        """
        self._filenames = stk.build(value)
        self.sort__filenames()

    def sort__filenames(self):
        """
        replace with something that pulls energy from hdr and
        sorts in energy order
        """
        pass

    def load_expimages(self):
        """
        Load the images
        """

        # TBD:  Add check here that all images are the same size,wcs, etc
        # TBD:  Add call to set min/max of X and Y to be limits of image

        self._crates = [pyc.IMAGECrate(ff, mode="r") for ff in self._filenames]
        self._livetime = 1.0 / self._crates[0].get_key_value("LIVETIME")

    def calc(self, pars, xlo, xhi=None, *args, **kwargs):
        """
        The calculation is simply to extract the same
        x,y pixel value from each image in the input exposure stack
        and returns those values.
        """
        if len(self._crates) != len(xlo):
            raise Exception("I don't know what I'm doing")
        vals = [ii.get_image().values[int(pars[0]), int(pars[1])]
                for ii in self._crates]
        vals = np.array(vals) * self._livetime
        if xhi is None:
            pass
        else:
            deltax = xhi - xlo
            vals = (vals / deltax)
        return vals


class ImageTMap():
    'Object to fit the temperature map data'

    def __init__(self, infiles, expfiles):
        'Setup'
        self.crates = None
        self.xlo = None
        self.ylo = None
        self.init_str = None
        self.ret_str = None
        self.savevals = None

        # Todo: check all images have same size
        # Todo: make sure images are in same order (energy-wise)
        self._load_image(infiles)
        self.expfiles = expfiles
        self._setup_exposure_model()

    def _load_image(self, infiles):
        """
        Load image files
        """
        file_name = stk.build(infiles)
        self.crates = [pyc.IMAGECrate(ff) for ff in file_name]
        #
        # Get energy range from header
        #
        self.xlo = np.array([f.get_key_value("ENERGYLO") for f in self.crates])
        self.xhi = np.array([f.get_key_value("ENERGYHI") for f in self.crates])

    def _setup_exposure_model(self):
        """
        Setup the exposure map model, only load once
        """

        # pylint: disable=undefined-variable
        # exposuremapstack is created by sherpa when the model is
        # registered.
        self.exposure_model = exposuremapstack.exposure_model()
        self.exposure_model.filename = self.expfiles

    def _do_fit(self, xypos, plot=None):
        """
        Perform a fit for a given x,y location
        """

        # pylint: disable=undefined-variable
        # pylint: disable=eval-used
        # pylint: disable=exec-used
        # pylint: disable=broad-except

        # Get the same x,y value from all images
        xpos = int(xypos[0])
        ypos = int(xypos[1])
        vals = np.array([ii.get_image().values[ypos, xpos] for ii in self.crates])

        # we check that at least 3 images have non-zero data
        idx, = np.where(vals != 0)
        if len(idx) < 3:
            return np.nan

        try:
            #
            # Load values.  Data are integrated
            #
            load_arrays(1, self.xlo, self.xhi, vals, Data1DInt)

            # Set the user definined source, then multiply that by the
            # exposure model
            srcmodel = eval(self.model)

            set_source(srcmodel * self.exposure_model)

            # inital settings, guesses, min, freeze/thaw, etc
            exec(self.init_str)

            # Setting x0,y0 values in the exposure model picks values
            # in the image
            self.exposure_model.x0 = xpos
            self.exposure_model.y0 = ypos

            fit()
            if plot:
                plot()

            retval = eval(self.ret_str) * 1.0

        except Exception as badfit:
            print(badfit)
            retval = np.nan

        return retval

    def set_source(self, model, init_str, ret_str):
        """
        Define the source model expression.
        The initialization string
        The vaule to return
        """

        self.model = model
        self.init_str = init_str
        self.ret_str = ret_str

    def __ifit(self, ipos, jpos, plot=None):
        """
        Do a single fit at one i,j location for diagnostics
        """
        self.do_fit([ipos-1, jpos-1], plot=plot)

    def fit(self):
        'For every pixel, fit the model and save the value'

        img_data = self.crates[0].get_image().values
        xlen = len(img_data[0])
        ylen = len(img_data)

        ipos = [float(x) for x in list(range(xlen)) * ylen]
        jpos = [float(x) for x in np.repeat(list(range(ylen)), xlen)]

        #
        # Something bad happens when I try to use parallel fit
        # here.  The returned results look garbled.
        # from sherpa.utils import parallel_map

        # ~~coords = np.array(zip(ii,jj))
        # ~~#np.random.shuffle(coords)

        coords = list(zip(ipos, jpos))

        # ~~od = parallel_map(self._do_fit, coords)
        # ~~od = map(self._do_fit, coords)
        outdata = [self._do_fit(c) for c in coords]

        self.savedata = np.zeros([ylen, xlen])

        for xypos, vals in zip(coords, outdata):
            self.savedata[int(xypos[1])][int(xypos[0])] = vals

        # ~~od = map(self._do_fit, zip(ii, jj))
        # ~~self.savedata = np.array(od).reshape([ylen, xlen])

    def save(self, outfile, clobber):
        '''
        Save the data; not even trying to copy header, WCS, etc.  Just
        create a simple image.
        '''
        outcrated = pyc.CrateData()
        outcrated.values = self.savedata
        outcratei = pyc.IMAGECrate()
        outcratei.add_image(outcrated)

        pyc.write_file(outcratei, outfile, clobber=clobber)

#
# Main Routine
#
@lw.handle_ciao_errors(TOOLNAME, __REVISION__)
def main():
    'Main routine'
    from ciao_contrib.param_soaker import get_params
    from ciao_contrib.runtool import add_tool_history

    # Load parameters
    pars = get_params(TOOLNAME, "rw", sys.argv,
                      verbose={"set": lw.set_verbosity, "cmd": VERB1})

    from ciao_contrib._tools.fileio import outfile_clobber_checks
    outfile_clobber_checks(pars["clobber"], pars["outfile"])

    add_model(ExposureMapStack)

    tmap = ImageTMap(pars["infile"], pars["expfile"])
    tmap.set_source(pars["srcmodel"], pars["initialization"],
                    pars["return_value"])
    tmap.fit()

    tmap.save(pars["outfile"], pars["clobber"])
    add_tool_history(pars["outfile"], TOOLNAME, pars,
                     toolversion=__REVISION__)


if __name__ == "__main__":
    main()
    sys.exit(0)
